name: Java CI Basic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: List files in repository
      run: ls -la
      
    - name: Create build directory
      run: mkdir -p build
      
    - name: Echo success message
      run: echo "Build environment setup successfully"
