name: Java CI with Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Compile Java files
      run: |
        # Find Java files and compile them if they exist
        find_result=$(find . -name "*.java" 2>/dev/null)
        if [ -n "$find_result" ]; then
          javac -d build $(find . -name "*.java") || echo "Compilation failed but continuing"
        else
          echo "No Java files found to compile"
        fi
      
    - name: Create JAR file
      run: |
        cd build
        jar cvf CleaningServiceApp.jar . || echo "JAR creation failed but continuing"
        ls -la
        
    - name: Create artifact text file
      run: |
        echo "This is a test artifact" > build/artifact.txt
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v3  # Try v3 instead of v4
      with:
        name: test-artifact
        path: build/artifact.txt
